name: Deploy React with Web3 on Surge with Yarn

on:
  push:
    branches: [ master ]
    paths:
    - 'client/**'
    
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: client
    name: Build and Deploy to Surge
    steps:
    - uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12
    
    - name: Directory
      run: pwd
      
    - uses: borales/actions-yarn@v2.0.0
      with: 
        cmd: install

    - name: Build App
      run: yarn build

    - name: Install Surge
      run: yarn global add surge
    - name: Run Surge
      run: surge ./build expense-tracker-ethereum.surge.sh --token ${{secrets.SURGE_TOKEN}}
